### PR TITLE
Fix the Dart representation of the `VARIANT` structure

### LINKED ISSUE #735: How to use IDispatch returned by IDispatch.invoke
I am trying to implement [this code for automating Excel in C++](https://learn.microsoft.com/en-us/previous-versions/office/troubleshoot/office-developer/automate-excel-from-c) in Dart, but the application crashes, when I am trying to use `pdispVal` property of the `VARAINT` result from `invoke` method.

The linked C++ code work perfectly on my computer, and here is my attempt to port it to Dart:

```Dart

int AutoWrap(int autoType, Pointer<VARIANT> pvResult, IDispatch pDisp, String member) {
  final IID_NULL = calloc<GUID>();
  final ptNameFunc = member.toNativeUtf16();
  final ptName = calloc<Pointer<Utf16>>()..value = ptNameFunc;
  final dispid = calloc<Int32>();

  try {
    final hr = pDisp.getIDsOfNames(IID_NULL, ptName.cast(), 1, LOCALE_USER_DEFAULT, dispid);
    if (FAILED(hr)) {
      throw WindowsException(hr);
    }
  } finally {
    free(ptNameFunc);
    free(ptName);
  }

  final args = calloc<DISPPARAMS>();

  try {
    final hr = pDisp.invoke(dispid.value, IID_NULL, LOCALE_SYSTEM_DEFAULT, autoType, args, pvResult, nullptr, nullptr);
    if (FAILED(hr)) {
      throw WindowsException(hr);
    } else {
      return hr;
    }
  } finally {
    free(args);
    free(dispid);
    free(IID_NULL);
  }
}

void main() {
  final hr = CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED);

  if (FAILED(hr)) {
    throw WindowsException(hr);
  }

  final clsid = calloc<GUID>();
  {
    final hr = CLSIDFromProgID("Excel.Application".toNativeUtf16(), clsid);

    if (FAILED(hr)) {
      free(clsid);
      throw WindowsException(hr);
    }
  }

  IDispatch pXlApp;
  {
    final ppv = calloc<COMObject>();
    final pIID_IDispatch = calloc<GUID>()..ref.setGUID(IID_IDispatch);
    final hr = CoCreateInstance(clsid, nullptr, CLSCTX_LOCAL_SERVER, pIID_IDispatch, ppv.cast());
    free(pIID_IDispatch);

    if (FAILED(hr)) {
      throw WindowsException(hr);
    }
    
    pXlApp = IDispatch(ppv);
  }

  {
    final result = calloc<VARIANT>();
    VariantInit(result);
    
    final hr = AutoWrap(
      DISPATCH_PROPERTYGET,
      result,
      pXlApp,
      "Name",
    );
    if (FAILED(hr)) {    
      throw WindowsException(hr);
    }
    print(result.ref.bstrVal.toDartString());
  }

  IDispatch pXlBooks;
  {
    final result = calloc<VARIANT>();
    VariantInit(result);

    final hr = AutoWrap(
      DISPATCH_PROPERTYGET,
      result,
      pXlApp,
      "Workbooks",
    );
    if (FAILED(hr)) {    
      throw WindowsException(hr);
    }
    
    pXlBooks = result.ref.pdispVal;
    pXlBooks.detach();
  }

  IDispatch pXlBook;
  {
    final result = calloc<VARIANT>();
    VariantInit(result);

    // Program crashes here
    final hr = AutoWrap(DISPATCH_PROPERTYGET, result, pXlBooks, "Add");
    if (FAILED(hr)) {    
      throw WindowsException(hr);
    }

    pXlBook = result.ref.pdispVal;
    pXlBook.detach();
  }
}
```

### PR DESCRIPTION
**Pull request by halildurmus**
Fixes #735

Some fields of the `VARIANT` were misrepresented, leading to the crash reported in issue #735. Added some tests to make sure the new representation of these fields is working properly.

### CODE REVIEW

File: lib/src/variant.dart [hunk 1]
```diff
@@ -35,7 +35,7 @@ import 'win32/oleaut32.g.dart';
 
 sealed class _VARIANT_Anonymous_3 extends Struct {
   external Pointer pvRecord;
-  external Pointer<COMObject> pRecInfo;
+  external COMObject pRecInfo;
```
Comment (domesticmouse) [inline lib/src/variant.dart]: Now that this isn't a pointer to `COMObject`, should the variable name be updated to `recInfo`?

File: lib/src/variant.dart [hunk 2]
```diff
@@ -63,8 +63,8 @@ sealed class _VARIANT_Anonymous_2 extends Union {
   @Double()
   external double date;
   external Pointer<Utf16> bstrVal;
-  external Pointer<COMObject> punkVal;
-  external Pointer<COMObject> pdispVal;
+  external COMObject punkVal;
```
Comment (domesticmouse) [inline lib/src/variant.dart]: `unkVal`?

**Review by domesticmouse — COMMENTED** [review]
Should the variable names be updated?

File: lib/src/variant.dart (hunk 1 above)
Comment (halildurmus) [reply lib/src/variant.dart]: The `COMObject` struct has a single field called `lpVtbl`, representing a Pointer to the COM v-table: https://github.com/dart-windows/win32/blob/ce8927ce81eb972bde92aaf4a2742631e9aa75b0/lib/src/combase.dart#L18-L27 which makes this struct identical to `VTablePointer`.

Nevertheless, I should just change these to `VTablePointer` to make things clearer.

**Review by domesticmouse — APPROVED** [review]
